// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 PopSolutions Cooperative

//! # ggml-spanker — GGML int4 matmul backend for the PopSolutions Sails
//!
//! Per ADR-001 (Rust runtime) and the cross-stream contract with
//! `popsolutions/MAST`. This crate exposes the [`MatmulInt4`]
//! trait — a Q4_K-shaped matrix-multiply primitive — together with
//! two implementations:
//!
//! - [`SailMatmul`]: the real-device path. Currently a stub
//!   returning [`Error::NotImplemented`] until the kernel driver
//!   gains `SPANKER_IOC_WORK_SUBMIT` (cross-stream Spanker #9,
//!   gated on the DDR3 work-dispatch PR).
//! - [`MockSail`]: a host-side mock that records the AXI4 traffic
//!   the matmul *would* issue, so unit tests can assert correctly-
//!   shaped transactions without a real device. Will be displaced
//!   for integration testing once Agent 1 exposes a queryable
//!   `axi4_mem_model` cocotb harness in MAST.
//!
//! ## Q4_K layout
//!
//! Mirrors upstream GGML's `block_q4_K` (256 weights packed into
//! 144 bytes: 4 bytes for `d` + `dmin` half-floats, 12 bytes of
//! 6-bit packed scales+mins, and 128 bytes of nibble-packed
//! weights). The `Q4_K_BLOCK_BYTES` constant is cross-checked
//! against this component layout in
//! `tests::q4_k_block_bytes_matches_component_layout`.
//!
//! ## bindgen
//!
//! The private [`ffi`] module is generated by `build.rs` from
//! `wrapper.h` → `src/driver/include/uapi/spanker_ioctl.h`. The
//! `bindgen_uapi_constants_match_runtime_mirror` test asserts the
//! generated types stay in sync with the runtime crate's
//! hand-mirrored layout.

#![warn(missing_docs)]
#![deny(unsafe_op_in_unsafe_fn)]

pub mod mock;
pub mod sail;

pub use mock::{MockSail, Transaction};
pub use sail::SailMatmul;

// bindgen-derived bindings over the spanker UAPI header. Generated
// by `build.rs` from `wrapper.h` → `src/driver/include/uapi/spanker_ioctl.h`.
// Surface today: SPANKER_IOC_MAGIC, SPANKER_ABI_VERSION_*, struct
// spanker_version. SPANKER_IOC_WORK_SUBMIT lands here automatically
// once the kernel-driver PR adds it to the UAPI header (gated on
// the DDR3 work-dispatch PR, cross-stream Spanker #9).
#[allow(
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

/// Number of weights packed into one Q4_K block. Mirrors
/// upstream GGML's `QK_K` constant.
pub const QK_K: usize = 256;

/// Bytes per Q4_K block. Mirrors upstream GGML's
/// `sizeof(block_q4_K)` (144 bytes: 12 bytes of scales + 128 bytes
/// of nibble-packed weights + 4 bytes of `d`/`dmin` half-floats).
pub const Q4_K_BLOCK_BYTES: usize = 144;

/// Bytes per element in the f32-shaped output the device returns
/// for a Q4_K matmul. The device dequantizes on the way out, so
/// `out` is `m × n` f32 values regardless of the input encoding.
///
/// Public so integration tests under `tests/` can compute the same
/// expected output-buffer size the production helpers use, without
/// re-declaring a local `const = 4` that could silently drift.
pub const OUTPUT_ELEM_BYTES: usize = 4;

/// Errors returned by this crate.
///
/// Marked `#[non_exhaustive]` so that adding new variants in
/// future minor releases (e.g. once `SPANKER_IOC_WORK_SUBMIT`
/// lands and brings device-specific error categories) is a
/// non-breaking change for downstream callers.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum Error {
    /// Caller passed dimensions that violate the Q4_K layout
    /// contract — either `k` is not a multiple of [`QK_K`], or
    /// the input slice lengths do not match the declared
    /// `m × k × n` shape under the Q4_K block size.
    #[error("bad dims: m={m} k={k} n={n}; require k % {qk} == 0 and slice lens consistent")]
    BadDims {
        /// Number of output rows.
        m: usize,
        /// Reduction dimension.
        k: usize,
        /// Number of output columns.
        n: usize,
        /// Required block size (i.e. [`QK_K`]).
        qk: usize,
    },

    /// The output buffer is smaller than the matmul requires.
    #[error("output buffer too small: have {have} bytes, need {need}")]
    OutputTooSmall {
        /// Bytes the caller provided.
        have: usize,
        /// Bytes the matmul actually needs.
        need: usize,
    },

    /// Real-device matmul is not yet wired up. Blocked on the
    /// kernel driver gaining `SPANKER_IOC_WORK_SUBMIT`, which in
    /// turn is gated on the DDR3 work-dispatch PR (cross-stream
    /// Spanker #9).
    #[error(
        "SailMatmul real-device path not implemented yet: \
         blocked on kernel driver SPANKER_IOC_WORK_SUBMIT \
         (cross-stream Spanker #9, DDR3 work-dispatch); \
         use MockSail for host-side testing"
    )]
    NotImplemented,

    /// Underlying runtime error (ioctl, open, etc.).
    #[error(transparent)]
    Runtime(#[from] spanker_runtime::Error),
}

/// Compute the byte length expected for an A operand of shape
/// `m × k` in Q4_K layout: `m × (k / QK_K) × Q4_K_BLOCK_BYTES`.
///
/// Returns `None` if `k` is not a positive multiple of [`QK_K`]
/// or if the arithmetic overflows `usize`.
pub(crate) fn expected_a_bytes(m: usize, k: usize) -> Option<usize> {
    if k == 0 || k % QK_K != 0 {
        return None;
    }
    let blocks_per_row = k / QK_K;
    m.checked_mul(blocks_per_row)?.checked_mul(Q4_K_BLOCK_BYTES)
}

/// Compute the byte length expected for a B operand of shape
/// `k × n` in Q4_K layout: `n × (k / QK_K) × Q4_K_BLOCK_BYTES`.
///
/// Returns `None` if `k` is not a positive multiple of [`QK_K`]
/// or if the arithmetic overflows `usize`.
pub(crate) fn expected_b_bytes(k: usize, n: usize) -> Option<usize> {
    if k == 0 || k % QK_K != 0 {
        return None;
    }
    let blocks_per_col = k / QK_K;
    n.checked_mul(blocks_per_col)?.checked_mul(Q4_K_BLOCK_BYTES)
}

/// Compute the byte length expected for the OUT operand of
/// shape `m × n`, dequantized into f32 at the device:
/// `m × n × OUTPUT_ELEM_BYTES`. Returns `None` on `usize`
/// overflow.
pub(crate) fn expected_out_bytes(m: usize, n: usize) -> Option<usize> {
    m.checked_mul(n)?.checked_mul(OUTPUT_ELEM_BYTES)
}

/// Convenience alias for results returned by this crate.
pub type Result<T> = std::result::Result<T, Error>;

/// Q4_K matrix multiplication primitive.
///
/// Inputs `a`, `b`, and `out` are raw byte slices in GGML's Q4_K
/// quantized layout. The matmul computes `out = a · b^T` in
/// row-major terms with shapes:
///
/// - `a`: `m × k` quantized weights (`k` MUST be a multiple of
///   [`QK_K`]).
/// - `b`: `k × n` quantized weights.
/// - `out`: `m × n` quantized weights, allocated by the caller.
pub trait MatmulInt4 {
    /// Issue a Q4_K matmul against the underlying device.
    fn matmul_q4_k(
        &self,
        a: &[u8],
        b: &[u8],
        out: &mut [u8],
        m: usize,
        k: usize,
        n: usize,
    ) -> Result<()>;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Cross-check Q4_K_BLOCK_BYTES by reconstructing it from the
    /// component-level layout (mirrors the C-side
    /// `static_assert(sizeof(block_q4_K) == 2*sizeof(ggml_half) +
    /// K_SCALE_SIZE + QK_K/2)` in upstream
    /// `external/ggml/src/ggml-common.h`).
    ///
    /// Replaces the prior tautological `assert_eq!(144, 144)`
    /// (review nit #5). A full bindgen cross-check against
    /// upstream GGML headers is deferred until ggml-spanker also
    /// binds `enum ggml_type`; doing so today would require
    /// pulling in GGML's full build graph for libclang, which
    /// gates on a bigger refactor than this PR's scope.
    #[test]
    fn q4_k_block_bytes_matches_component_layout() {
        const GGML_HALF_BYTES: usize = 2;
        const K_SCALE_SIZE: usize = 12;
        let component_total = 2 * GGML_HALF_BYTES // d + dmin
            + K_SCALE_SIZE                        // 6-bit packed scales+mins
            + QK_K / 2; //                          4-bit nibble-packed weights
        assert_eq!(
            Q4_K_BLOCK_BYTES, component_total,
            "Q4_K_BLOCK_BYTES drifted from the GGML block_q4_K layout"
        );
        assert_eq!(QK_K, 256, "QK_K is fixed by the GGML quant ABI");
    }

    /// Bindgen smoke test — confirms the spanker UAPI header was
    /// successfully bound by `build.rs`. The `struct spanker_version`
    /// wire format is 8 bytes (4 × `__u16`), and the `SPANKER_IOC_MAGIC`
    /// constant pulled from the C header MUST match the byte the
    /// runtime crate's hand-mirrored ioctl macros use.
    ///
    /// If this test fails, either the header drifted or the runtime
    /// crate's mirror lost sync — both are wire-ABI breaks.
    #[test]
    fn bindgen_uapi_constants_match_runtime_mirror() {
        assert_eq!(
            core::mem::size_of::<ffi::spanker_version>(),
            8,
            "spanker_version is wire-stable at 8 bytes"
        );
        assert_eq!(ffi::SPANKER_IOC_MAGIC, 0xE3);
        assert_eq!(
            ffi::SPANKER_ABI_VERSION_MAJOR as u16,
            spanker_runtime::ABI_VERSION_MAJOR
        );
        assert_eq!(
            ffi::SPANKER_ABI_VERSION_MINOR as u16,
            spanker_runtime::ABI_VERSION_MINOR
        );
        assert_eq!(
            ffi::SPANKER_ABI_VERSION_PATCH as u16,
            spanker_runtime::ABI_VERSION_PATCH
        );
    }

    #[test]
    fn expected_a_bytes_rejects_unaligned_or_zero_k() {
        assert_eq!(expected_a_bytes(4, 0), None);
        assert_eq!(expected_a_bytes(4, 100), None);
        // 4 rows × 1 block-per-row × Q4_K_BLOCK_BYTES bytes-per-block.
        assert_eq!(expected_a_bytes(4, QK_K), Some(4 * Q4_K_BLOCK_BYTES));
        assert_eq!(
            expected_a_bytes(0, QK_K),
            Some(0),
            "m=0 with valid k yields zero bytes (no-op)"
        );
    }

    #[test]
    fn expected_b_bytes_matches_n_times_blocks_per_col() {
        assert_eq!(expected_b_bytes(QK_K, 4), Some(4 * Q4_K_BLOCK_BYTES));
        assert_eq!(
            expected_b_bytes(2 * QK_K, 4),
            Some(4 * 2 * Q4_K_BLOCK_BYTES)
        );
        assert_eq!(expected_b_bytes(QK_K - 1, 4), None);
    }

    #[test]
    fn expected_out_bytes_is_m_times_n_times_f32() {
        assert_eq!(expected_out_bytes(4, 4), Some(4 * 4 * OUTPUT_ELEM_BYTES));
        assert_eq!(expected_out_bytes(0, 4), Some(0));
        assert_eq!(expected_out_bytes(4, 0), Some(0));
    }
}
